import = ["/home/mpp/configs/dotfiles/alacritty/.config/alacritty/themes/everforest_dark.toml"]

[env]
TERM = "alacritty"

[font]
size = 16.0

[font.bold]
family = "JetBrainsMono Nerd Font"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"

[font.italic]
family = "JetBrainsMono Nerd Font"

[font.normal]
family = "JetBrainsMono Nerd Font"

[font.offset]
x = 0
y = 0

[window]
decorations = "full"
dynamic_title = true
opacity = 0.7
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 0
y = 0
